import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import StoreProvider from "@/store/StoreProvider";
import I18nProvider from "@/lib/I18nProvider";
import Header from "@/components/Basic/Header";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <I18nProvider>
            <StyledComponentsRegistry>
              <Header />
              {children}
            </StyledComponentsRegistry>
          </I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
