import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import StyledComponentsRegistry from "@/lib/registry";
import StoreProvider from "@/store/StoreProvider";
import I18nProvider from "@/lib/I18nProvider";
import Header from "@/components/Basic/Header";
import Web3Provider from "@/lib/web3/Web3Provider";


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <I18nProvider>
            <Web3Provider>
              <StyledComponentsRegistry>
                <Header />
                {children}
              </StyledComponentsRegistry>
            </Web3Provider>
          </I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
